name: TDD_test_react_lektion4

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.8.0'

      - name: Change to React project directory
        working-directory: src/main/react/lektion4/LEKTION-4-REACT
        run: echo "Changed directory to React project"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: src/main/react/lektion4/LEKTION-4-REACT/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('src/main/react/lektion4/LEKTION-4-REACT/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: src/main/react/lektion4/LEKTION-4-REACT
        run: npm install

      - name: Run tests
        working-directory: src/main/react/lektion4/LEKTION-4-REACT
        run: npm test
